name: Deploy GitHub Pages
permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Instalar dependências
        run: npm install
      
      - name: Build do projeto
        run: npm run build
      
      - name: Verificar conteúdo do build
        run: |
          if [ -d "./build" ]; then
            ls -la ./build;
          else
            echo "Pasta build não encontrada. Verifique seu comando de build.";
            exit 1;
          fi
      
      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./build
          user_name: 'Antonio Juevan'           
          user_email: 'antoniojuevan@gmail.com'  
