name: Deploy GitHub Pages
permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Instalar dependências
        run: npm install
      
      - name: Build do projeto
        run: npm run build
      
      - name: Verificar conteúdo do build
        run: ls -la ./build
      
      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}  # certifique-se que este secret está configurado corretamente com um PAT válido
          publish_dir: ./build
          user_name: 'Antonio Juevan'           # adicione seu nome de usuário aqui
          user_email: 'antoniojuevan@gmail.com'  # adicione seu email aqui
